[project]
name = "qtf-mcp"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["mcp[cli]>=1.22", "qtf", "ta-lib>=0.6.8"]

[tool.uv.sources]
qtf = { path = "libs/qtf-0.2.0-cp310-abi3-manylinux_2_28_x86_64.whl" }
